# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 94a33f84b65e1f903f999561c868286e7aa27b7a5c55ae8e0f20440e11623f990f0346652dff430376b9a3e2ab0afd30731c111ad64709786c1ee8708ec1c327

test:
  secret_key_base: ea4475b853fe692da78c51c34abc4b00f1dbb8bc7bd665628dfb3db4199635450a41cfb3545de261c3eebb8bfd1a7d4493717a2854405f9b2ad5ad251318c6c4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
